[package]
name = "mock-educator-verification-nft"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib", "lib"]
doctest = false

[dependencies]
soroban-sdk = "20.1.0"

[profile.release]
opt-level = 'z'
overflow-checks = true
debug = 0
strip = true
debug-assertions = false
panic = 'abort'
codegen-units = 1
lto = true