[package]
name = "content-search-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "22.0.0-rc.3.2", features = ["testutils"] }

[dev-dependencies]
soroban-sdk = { version = "22.0.0-rc.3.2", features = ["testutils"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
